# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-12 14:53
from __future__ import unicode_literals

import apps.user.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='picture',
            field=models.ImageField(blank=True, null=True, upload_to=apps.user.models.get_image_path),
        ),
    ]
