# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-17 07:45
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_user_picture'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='followed_users', to=settings.AUTH_USER_MODEL),
        ),
    ]
