# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:37
from __future__ import unicode_literals

import apps.activities.models
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Activity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity_date', models.DateField()),
                ('duration', models.DurationField()),
                ('pauses', models.DurationField()),
                ('distance', models.DecimalField(decimal_places=2, max_digits=5)),
                ('min_alt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_alt', models.DecimalField(decimal_places=2, max_digits=5)),
                ('descent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ascent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('max_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('ave_speed', models.DecimalField(decimal_places=2, max_digits=5)),
                ('creation_date', models.DateField(auto_now_add=True)),
                ('modification_date', models.DateField(auto_now=True)),
            ],
            options={
                'db_table': 'activities',
            },
        ),
        migrations.CreateModel(
            name='Gpx',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('gpx_file', models.FileField(upload_to=apps.activities.models.user_directory_path)),
            ],
            options={
                'db_table': 'gpx',
            },
        ),
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'sports',
            },
        ),
        migrations.AddField(
            model_name='activity',
            name='gpx',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='activities.Gpx'),
        ),
        migrations.AddField(
            model_name='activity',
            name='sport',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='activities.Sport'),
        ),
        migrations.AddField(
            model_name='activity',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
