# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 12:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='activity',
            options={'verbose_name': 'activity', 'verbose_name_plural': 'activities'},
        ),
        migrations.AlterModelOptions(
            name='gpx',
            options={'verbose_name': 'gpx', 'verbose_name_plural': 'gpx'},
        ),
        migrations.AlterModelOptions(
            name='sport',
            options={'verbose_name': 'sport', 'verbose_name_plural': 'sports'},
        ),
    ]
