# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20171009_1248'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='gpx',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='activities.Gpx'),
        ),
    ]
