# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_auto_20171009_1457'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gpx',
            name='gpx_file',
            field=models.FileField(upload_to='gpx/%Y/%m/%d/'),
        ),
    ]
