# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-09 16:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0004_auto_20171009_1616'),
    ]

    operations = [
        migrations.AddField(
            model_name='activity',
            name='moving',
            field=models.DurationField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ascent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='ave_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='descent',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='distance',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_alt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='max_speed',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='min_alt',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='pauses',
            field=models.DurationField(blank=True, null=True),
        ),
    ]
