# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-10-10 09:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0005_auto_20171009_1620'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activity',
            name='activity_date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='activity',
            name='creation_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='activity',
            name='modification_date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
